### PR TITLE
Fix the equal volumn expression 

### PR DESCRIPTION
**Pull request by Usami-Renko**
fix the equal volumn expression for prolate spheroid and cylinder

### CODE REVIEW

**Comment by jleinonen** [comment]
Hi @Usami-Renko ,

Could you explain why this change is needed? We looked at these in #20.

**Comment by Usami-Renko** [comment]
The geometric consideration is that the diameter of circumscribe sphere of any cylinder is sqrt(h**2+d**2), where h is the height of the cylinder (rotational axis), d is the diameter of the base circle (horizontal axis).

**Comment by Usami-Renko** [comment]
Hi, @jleinonen ,
Please take a look at my response and let me know why classification of cylinders are needed, it seems stange to me.

**Comment by jleinonen** [comment]
The way it works now is by using the maximum of the half-height of the cylinder and the radius as the maximum dimension. This is actually consistent with how the dimension of scatterers is defined for snowflakes, for instance.

I think it's best not to do this change as it will break existing behavior. However if you want to contribute an option to use your definition I would be open to that.

**Comment by Usami-Renko** [comment]
@jleinonen 
Okay, I will make a user option for that issue and resubmit the pull request soon.

**Pull request closed without merging**
